//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace MvcAppSale.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class saleModels : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new saleModels object using the connection string found in the 'saleModels' section of the application configuration file.
        /// </summary>
        public saleModels() : base("name=saleModels", "saleModels")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new saleModels object.
        /// </summary>
        public saleModels(string connectionString) : base(connectionString, "saleModels")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new saleModels object.
        /// </summary>
        public saleModels(EntityConnection connection) : base(connection, "saleModels")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sale> sales
        {
            get
            {
                if ((_sales == null))
                {
                    _sales = base.CreateObjectSet<sale>("sales");
                }
                return _sales;
            }
        }
        private ObjectSet<sale> _sales;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<salesdt> salesdts
        {
            get
            {
                if ((_salesdts == null))
                {
                    _salesdts = base.CreateObjectSet<salesdt>("salesdts");
                }
                return _salesdts;
            }
        }
        private ObjectSet<salesdt> _salesdts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<mscustomer> mscustomers
        {
            get
            {
                if ((_mscustomers == null))
                {
                    _mscustomers = base.CreateObjectSet<mscustomer>("mscustomers");
                }
                return _mscustomers;
            }
        }
        private ObjectSet<mscustomer> _mscustomers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<msfood> msfoods
        {
            get
            {
                if ((_msfoods == null))
                {
                    _msfoods = base.CreateObjectSet<msfood>("msfoods");
                }
                return _msfoods;
            }
        }
        private ObjectSet<msfood> _msfoods;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sales EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosales(sale sale)
        {
            base.AddObject("sales", sale);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the salesdts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosalesdts(salesdt salesdt)
        {
            base.AddObject("salesdts", salesdt);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the mscustomers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomscustomers(mscustomer mscustomer)
        {
            base.AddObject("mscustomers", mscustomer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the msfoods EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomsfoods(msfood msfood)
        {
            base.AddObject("msfoods", msfood);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="saleModel", Name="mscustomer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class mscustomer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new mscustomer object.
        /// </summary>
        /// <param name="custcode">Initial value of the custcode property.</param>
        /// <param name="custname">Initial value of the custname property.</param>
        /// <param name="address">Initial value of the address property.</param>
        /// <param name="phone">Initial value of the phone property.</param>
        public static mscustomer Createmscustomer(global::System.String custcode, global::System.String custname, global::System.String address, global::System.String phone)
        {
            mscustomer mscustomer = new mscustomer();
            mscustomer.custcode = custcode;
            mscustomer.custname = custname;
            mscustomer.address = address;
            mscustomer.phone = phone;
            return mscustomer;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String custcode
        {
            get
            {
                return _custcode;
            }
            set
            {
                if (_custcode != value)
                {
                    OncustcodeChanging(value);
                    ReportPropertyChanging("custcode");
                    _custcode = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("custcode");
                    OncustcodeChanged();
                }
            }
        }
        private global::System.String _custcode;
        partial void OncustcodeChanging(global::System.String value);
        partial void OncustcodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String custname
        {
            get
            {
                return _custname;
            }
            set
            {
                OncustnameChanging(value);
                ReportPropertyChanging("custname");
                _custname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("custname");
                OncustnameChanged();
            }
        }
        private global::System.String _custname;
        partial void OncustnameChanging(global::System.String value);
        partial void OncustnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String address
        {
            get
            {
                return _address;
            }
            set
            {
                OnaddressChanging(value);
                ReportPropertyChanging("address");
                _address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("address");
                OnaddressChanged();
            }
        }
        private global::System.String _address;
        partial void OnaddressChanging(global::System.String value);
        partial void OnaddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String phone
        {
            get
            {
                return _phone;
            }
            set
            {
                OnphoneChanging(value);
                ReportPropertyChanging("phone");
                _phone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("phone");
                OnphoneChanged();
            }
        }
        private global::System.String _phone;
        partial void OnphoneChanging(global::System.String value);
        partial void OnphoneChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="saleModel", Name="msfood")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class msfood : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new msfood object.
        /// </summary>
        /// <param name="foodcode">Initial value of the foodcode property.</param>
        /// <param name="foodname">Initial value of the foodname property.</param>
        /// <param name="price">Initial value of the price property.</param>
        public static msfood Createmsfood(global::System.String foodcode, global::System.String foodname, global::System.Decimal price)
        {
            msfood msfood = new msfood();
            msfood.foodcode = foodcode;
            msfood.foodname = foodname;
            msfood.price = price;
            return msfood;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String foodcode
        {
            get
            {
                return _foodcode;
            }
            set
            {
                if (_foodcode != value)
                {
                    OnfoodcodeChanging(value);
                    ReportPropertyChanging("foodcode");
                    _foodcode = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("foodcode");
                    OnfoodcodeChanged();
                }
            }
        }
        private global::System.String _foodcode;
        partial void OnfoodcodeChanging(global::System.String value);
        partial void OnfoodcodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String foodname
        {
            get
            {
                return _foodname;
            }
            set
            {
                OnfoodnameChanging(value);
                ReportPropertyChanging("foodname");
                _foodname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("foodname");
                OnfoodnameChanged();
            }
        }
        private global::System.String _foodname;
        partial void OnfoodnameChanging(global::System.String value);
        partial void OnfoodnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal price
        {
            get
            {
                return _price;
            }
            set
            {
                OnpriceChanging(value);
                ReportPropertyChanging("price");
                _price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("price");
                OnpriceChanged();
            }
        }
        private global::System.Decimal _price;
        partial void OnpriceChanging(global::System.Decimal value);
        partial void OnpriceChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="saleModel", Name="sale")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sale : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sale object.
        /// </summary>
        /// <param name="transno">Initial value of the transno property.</param>
        /// <param name="custcode">Initial value of the custcode property.</param>
        /// <param name="totalamount">Initial value of the totalamount property.</param>
        public static sale Createsale(global::System.String transno, global::System.String custcode, global::System.Decimal totalamount)
        {
            sale sale = new sale();
            sale.transno = transno;
            sale.custcode = custcode;
            sale.totalamount = totalamount;
            return sale;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String transno
        {
            get
            {
                return _transno;
            }
            set
            {
                if (_transno != value)
                {
                    OntransnoChanging(value);
                    ReportPropertyChanging("transno");
                    _transno = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("transno");
                    OntransnoChanged();
                }
            }
        }
        private global::System.String _transno;
        partial void OntransnoChanging(global::System.String value);
        partial void OntransnoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String custcode
        {
            get
            {
                return _custcode;
            }
            set
            {
                if (_custcode != value)
                {
                    OncustcodeChanging(value);
                    ReportPropertyChanging("custcode");
                    _custcode = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("custcode");
                    OncustcodeChanged();
                }
            }
        }
        private global::System.String _custcode;
        partial void OncustcodeChanging(global::System.String value);
        partial void OncustcodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> transdate
        {
            get
            {
                return _transdate;
            }
            set
            {
                OntransdateChanging(value);
                ReportPropertyChanging("transdate");
                _transdate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("transdate");
                OntransdateChanged();
            }
        }
        private Nullable<global::System.DateTime> _transdate;
        partial void OntransdateChanging(Nullable<global::System.DateTime> value);
        partial void OntransdateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal totalamount
        {
            get
            {
                return _totalamount;
            }
            set
            {
                OntotalamountChanging(value);
                ReportPropertyChanging("totalamount");
                _totalamount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("totalamount");
                OntotalamountChanged();
            }
        }
        private global::System.Decimal _totalamount;
        partial void OntotalamountChanging(global::System.Decimal value);
        partial void OntotalamountChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="saleModel", Name="salesdt")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class salesdt : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new salesdt object.
        /// </summary>
        /// <param name="transno">Initial value of the transno property.</param>
        /// <param name="foodcode">Initial value of the foodcode property.</param>
        public static salesdt Createsalesdt(global::System.String transno, global::System.String foodcode)
        {
            salesdt salesdt = new salesdt();
            salesdt.transno = transno;
            salesdt.foodcode = foodcode;
            return salesdt;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String transno
        {
            get
            {
                return _transno;
            }
            set
            {
                if (_transno != value)
                {
                    OntransnoChanging(value);
                    ReportPropertyChanging("transno");
                    _transno = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("transno");
                    OntransnoChanged();
                }
            }
        }
        private global::System.String _transno;
        partial void OntransnoChanging(global::System.String value);
        partial void OntransnoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String foodcode
        {
            get
            {
                return _foodcode;
            }
            set
            {
                if (_foodcode != value)
                {
                    OnfoodcodeChanging(value);
                    ReportPropertyChanging("foodcode");
                    _foodcode = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("foodcode");
                    OnfoodcodeChanged();
                }
            }
        }
        private global::System.String _foodcode;
        partial void OnfoodcodeChanging(global::System.String value);
        partial void OnfoodcodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> qty
        {
            get
            {
                return _qty;
            }
            set
            {
                OnqtyChanging(value);
                ReportPropertyChanging("qty");
                _qty = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("qty");
                OnqtyChanged();
            }
        }
        private Nullable<global::System.Int32> _qty;
        partial void OnqtyChanging(Nullable<global::System.Int32> value);
        partial void OnqtyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> amount
        {
            get
            {
                return _amount;
            }
            set
            {
                OnamountChanging(value);
                ReportPropertyChanging("amount");
                _amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("amount");
                OnamountChanged();
            }
        }
        private Nullable<global::System.Decimal> _amount;
        partial void OnamountChanging(Nullable<global::System.Decimal> value);
        partial void OnamountChanged();

        #endregion

    
    }

    #endregion

    
}
